# Generated by Django 4.0 on 2022-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_setoftheday_mealssetofthedaymealsoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoftheday',
            name='mealsOfTheDay',
            field=models.ManyToManyField(through='meals.MealsSetofthedayMealsoftheday', to='meals.MealOfTheDay'),
        ),
    ]
