# Generated by Django 4.0 on 2022-02-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_setoftheday_mealsoftheday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealoftheday',
            name='active',
        ),
    ]
