# Generated by Django 4.0 on 2022-02-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_mealoftheday_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoftheday',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
