# Generated by Django 4.0 on 2022-02-22 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 2, 22, 18, 30, 48, 75639))),
            ],
        ),
    ]
