# Generated by Django 3.2.9 on 2021-12-15 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=250)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 12, 15, 20, 7, 46, 635810))),
            ],
        ),
    ]
