# Generated by Django 4.0 on 2021-12-21 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 13, 55, 45, 393112)),
        ),
    ]
