# Generated by Django 4.0 on 2022-02-20 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_reservation_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 26, 58, 983913)),
        ),
    ]
