# Generated by Django 3.2.9 on 2021-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0002_user_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visit_time',
            field=models.DateTimeField(default=None),
        ),
    ]
